# this is sample Gemfile
ruby '3.2.2'

gem 'rails', '~> 6.1.4'
# comment
gem 'bootsnap', '>= 1.4.4', require: false

gem 'kaminari'
gem 'paranoia' #comment

group :development do
  gem 'listen', '~> 3.3'
  gem 'spring'
end
